version: "3.8"

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - payment-service

  
  # Order Service + Postgres
  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  order-service:
    build: ./order-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - order-db

  # Payment Service + Postgres
  payment-db:
    image: postgres:15
    environment:
      POSTGRES_DB: paymentdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  payment-service:
    build: ./payment-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/paymentdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - payment-db

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      # Для корректного отслеживания файлов в Alpine
      CHOKIDAR_USEPOLLING: "true"

volumes:
  order-db-data:
  payment-db-data:
